/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
                  "secondary-fixed": "#68fcbf",
                  "on-error-container": "#93000a",
                  "surface-container-highest": "#e3e1ec",
                  "primary-fixed-dim": "#4edea3",
                  "on-surface": "#1a1b22",
                  "inverse-primary": "#4edea3",
                  "surface-container-low": "#f4f2fd",
                  "on-secondary-container": "#00714e",
                  "primary": "#006c49",
                  "tertiary-fixed": "#e2e2e3",
                  "background": "#fbf8ff",
                  "on-secondary-fixed": "#002114",
                  "outline-variant": "#bbcabf",
                  "surface-container-high": "#e8e7f1",
                  "surface-dim": "#dad9e3",
                  "on-primary-container": "#00422b",
                  "inverse-surface": "#2f3038",
                  "primary-container": "#10b981",
                  "surface": "#fbf8ff",
                  "inverse-on-surface": "#f1effa",
                  "surface-bright": "#fbf8ff",
                  "primary-fixed": "#6ffbbe",
                  "on-tertiary-fixed-variant": "#454748",
                  "on-error": "#ffffff",
                  "on-primary": "#ffffff",
                  "error-container": "#ffdad6",
                  "on-surface-variant": "#3c4a42",
                  "tertiary": "#5d5e60",
                  "tertiary-fixed-dim": "#c6c6c7",
                  "tertiary-container": "#a2a3a4",
                  "surface-tint": "#006c49",
                  "outline": "#6c7a71",
                  "secondary-fixed-dim": "#45dfa4",
                  "on-secondary": "#ffffff",
                  "secondary-container": "#64f9bc",
                  "on-primary-fixed-variant": "#005236",
                  "on-secondary-fixed-variant": "#005137",
                  "on-background": "#1a1b22",
                  "on-primary-fixed": "#002113",
                  "secondary": "#006c4b",
                  "surface-container": "#eeedf7",
                  "surface-container-lowest": "#ffffff",
                  "on-tertiary-container": "#38393b",
                  "surface-variant": "#e3e1ec",
                  "on-tertiary": "#ffffff",
                  "error": "#ba1a1a",
                  "on-tertiary-fixed": "#1a1c1d"
          },
          "borderRadius": {
                  "DEFAULT": "0.25rem",
                  "lg": "0.5rem",
                  "xl": "0.75rem",
                  "full": "9999px"
          },
          "spacing": {
                  "lg": "24px",
                  "sm": "8px",
                  "md": "16px",
                  "base": "8px",
                  "container-margin-mobile": "16px",
                  "container-margin-desktop": "40px",
                  "xs": "4px",
                  "xl": "32px",
                  "gutter": "16px"
          },
          "fontFamily": {
                  "body-lg": ["Inter"],
                  "body-md": ["Inter"],
                  "display-lg-mobile": ["Inter"],
                  "display-lg": ["Inter"],
                  "label-sm": ["Inter"],
                  "headline-sm": ["Inter"],
                  "headline-md": ["Inter"],
                  "label-md": ["Inter"]
          },
          "fontSize": {
                  "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                  "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                  "display-lg-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                  "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                  "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
                  "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                  "headline-md": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                  "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}]
          }
      },
  },
  plugins: [],
}
